const {ATTRIBUTE_CLASS_PATH, BOOTSTRAP_PATH, COMPILER_DIR, TAG_CLASS_PATH, COMPONENT_CLASS_PATH, CHILD_COMPONENT_CLASS_PATH, HTML_COMPILER_PATH} = require('./constants');

const globalize = require('./../bootstrap/globals');

globalize({
    ATTRIBUTE_CLASS_PATH,
    COMPILER_DIR,
    TAG_CLASS_PATH,
    COMPONENT_CLASS_PATH,
    CHILD_COMPONENT_CLASS_PATH,
    HTML_COMPILER_PATH,
    BOOTSTRAP_PATH,
});